### PR TITLE
Fix english and rename to .min.js

### PR DESCRIPTION
**Pull request by moeenio**
In english, words that describes some word are **after** the word, so it's for example "ScratchEco Settings"
Also, **you** target a person, to target his thing(s), use **your**

### CODE REVIEW

**Comment by moeenio** [comment]
Also, please use GitHub Pages with a gh-pages branch on this repo. 000webhost are scam, and they can take down your site at any time.

**Comment by goosesima** [comment]
Readme fixed

**Comment by goosesima** [comment]
> Also, please use GitHub Pages with a gh-pages branch on this repo. 000webhost are scam, and they can take down your site at any time.

I have server on discord where i develop scratchEco https://discord.gg/eMrvjDF

**Comment by moeenio** [comment]
for the ext website

**Comment by moeenio** [comment]
And, could you merge the request ?

**Comment by moeenio** [comment]
> > Also, please use GitHub Pages with a gh-pages branch on this repo. 000webhost are scam, and they can take down your site at any time.
> 
> I have server on discord where i develop scratchEco [discord.gg/eMrvjDF](https://discord.gg/eMrvjDF)

I'm saying to use GH pages for the extension's website

**Pull request closed without merging**
